repos:
  - repo: https://github.com/doublify/pre-commit-rust
    rev: v1.0
    hooks:
      - id: fmt
        name: cargo fmt firmware
        args: [--manifest-path, firmware/Cargo.toml, --, --check]
